apiVersion: skaffold/v4beta8
kind: Config
metadata:
  name: user-service
#build:
#  artifacts:
#    - image: x-mister/user-service-dev
#      docker:
#        dockerfile: Dockerfile
#  local: {}
manifests:
  rawYaml:
#    - k8s/app*
    - k8s/psql*
    # - k8s/rabbit*
    - k8s/keycloak*