apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-sb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak-sb
  template:
    metadata:
      labels:
        app: keycloak-sb
    spec:
      containers:
        - name: keycloak-sb
          image: x-mister/authentication-service:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
#            - name: SPRING_DATASOURCE_URL
#              value: jdbc:postgresql://postgres:5432/postgres
#            - name: SPRING_DATASOURCE_USERNAME
#              value: postgres
#            - name: SPRING_DATASOURCE_PASSWORD
#              value: postgres
          ports:
            - containerPort: 8081
