apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: keycloak
spec:
  serviceName: keycloak-service
  replicas: 1
  selector:
      matchLabels:
        app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:23.0.4
          args: ["start-dev"]
          env:
            - name: KEYCLOAK_ADMIN
              value: admin
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: admin
            - name: KEYCLOAK_USER
              value: user
            - name: KEYCLOAK_PASSWORD
              value: user
            - name: DB_VENDOR
              value: POSTGRES
            - name: KC_DB_URL
              value: jdbc:postgresql://keycloak-db-service:5432/postgres
            - name: KC_DB
              value: postgres
            - name: KC_DB_USERNAME
              value: postgres
            - name: KC_DB_PASSWORD
              value: postgres
          ports:
            - containerPort: 8080
              name: keycloak
          volumeMounts:
            - name: keycloak-persistence-storage
              mountPath: /var/lib/keycloak/data
#            - name: realm-config
#              mountPath: /opt/keycloak/realms
      volumes:
        - name: keycloak-persistence-storage
          persistentVolumeClaim:
            claimName: keycloak-pv-claim
#        - name: realm-config
#          configMap:
#            name: keycloak-config