apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-config
data:
 realm.json: |
  {
    "id": "pcpartshop-realm",
    "realm": "pcpartshop-realm",
    "enabled": true,
    "users":
    [
      {
        "username": "john.doe",
        "enabled": true,
        "emailVerified": true,
        "firstName": "John",
        "lastName": "Doe",
        "email": "john.doe@example.com",
        "credentials": [
          {
            "type": "password",
            "value": "password",
            "temporary": false
          }
        ]
      },
      {
        "username": "jane.doe",
        "enabled": true,
        "emailVerified": true,
        "firstName": "Jane",
        "lastName": "Doe",
        "email": "jane.doe@example.com",
        "credentials": [
          {
            "type": "password",
            "value": "password",
            "temporary": false
          }
        ],
        "realmRoles": ["user"]
      }
    ],
    "clients": 
    [
      {
        "clientId": "pcpartshop-client",
        "name": "pcpartshop-client",
        "directAccessGrantsEnabled": true,
        "redirectUris": ["http://localhost:8080/*"],
        "publicClient": true
      } 
    ]
  }