apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kc-db-pv-claim
  labels:
    app: keycloak-db
    tier: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
