apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: keycloak-db
  labels:
    app: keycloak-db
    tier: database
spec:
  serviceName: keycloak-db
  replicas: 1
  selector:
    matchLabels:
      app: keycloak-db
  template:
    metadata:
      labels:
        app: keycloak-db
        tier: database
    spec:
      containers:
        - name: keycloak-db
          image: postgres:12
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_DB
              value: postgres
          ports:
            - containerPort: 5432
              name: keycloak-db
          volumeMounts:
            - name: postgres-persistence-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-persistence-storage
          persistentVolumeClaim:
            claimName: kc-db-pv-claim
